$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: hvac-train-and-llm-diagnostic
description: Train HVAC failure model and run LLM-based diagnostics.

settings:
  default_compute: azureml:cpu-cluster   # or whatever your compute is called

jobs:
  train:
    type: command
    component: file:./components/train.yml     # <— FIXED
    inputs:
      n_units: 25
      days: 60
      freq_minutes: 15

  llm_diag:
    type: command
    component: file:./components/llm_diagnostic.yml   # <— FIXED
    inputs:
      metrics: ${{parent.jobs.train.outputs.metrics}}
