$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

display_name: hvac-failure-train-job
experiment_name: hvac-failure-experiments
description: >
  Train a RandomForest model to predict HVAC failures within 24 hours
  using synthetic sensor data, and log metrics for downstream deployment.

code: ..

command: >
  pip install -q azureml-mlflow scikit-learn pandas numpy joblib openai &&
  python ml/training/train_anomaly_model.py --n-units 25 --days 60 --freq-minutes 15 --output-model-path outputs/model/hvac_failure_rf_model.pkl --output-metrics-path outputs/model/hvac_failure_metrics.json

environment_variables:
  AZURE_OPENAI_ENDPOINT: "https://calvi-mi5r2d07-eastus2.cognitiveservices.azure.com/"
  AZURE_OPENAI_DEPLOYMENT: "gpt-4o-mini"
  AZURE_OPENAI_API_VERSION: "2025-01-01-preview"

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

compute: azureml:cpu-cluster

outputs:
  model_dir:
    type: uri_folder
    mode: rw_mount
    path: azureml://datastores/workspaceblobstore/paths/hvac-failure-model/
